### ISSUE TITLE
Somthing's broken with the dashboard

### ISSUE THREAD

**Issue by itamarhaber** [RedisGears/EdgeRealtimeVideoAnalytics#19]
All graphs excluding FPS display 'No data points'.

**Comment by narfai** [comment]
Hello !

Grafana is requesting timeseries with a millisecond timestamp, while the gear add `prf_` values with second timestamp, making those never shown.

I managed to get it worked by the removing a division `app/gear` line 198 :
```
ts = ref_msec // 1000
```
to 
```
ts = ref_msec
```

There also may be a way to ask grafana to query timeseries with seconds instead of milliseconds...
