### ISSUE TITLE
Documentation on module redisAI - Explanation of code in gear.py

### ISSUE THREAD

**Issue by dsmanl** [RedisGears/EdgeRealtimeVideoAnalytics#24]
Dear all,

I am just starting to learn more about RedisGears and RedisAI.

The examples provided are very helpful. Thanks for these! Unfortunately I can't reproduce parts completely, because I can't find any documentation for the module redisAI, which is imported and used in [gears.py](https://github.com/RedisGears/EdgeRealtimeVideoAnalytics/blob/master/app/gear.py). For example, where can I find a list of implemented methods and functions with explanations and examples, like `redisAI.createTensorFromBlob`?

I am grateful for any help and apologize in advance if I missed something.

Thanks!

**Comment by MeirShpilraien** [comment]
Hey @dsmanl, you can not find it because it's native C implementation, provided by RedisGears, and allows you to directly interact with RedisAI module. We are working on the document this API now until then you can look here to see all the available functions https://github.com/RedisGears/RedisGears/blob/c9d765e099239c9c69a5f4ff247a41b2e180a969/src/redisgears_python.c#L2979 (Notice, depends on the version you are using, this API might have changed a little and some errors check was added to prevent crashing on misuse).

**Comment by dsmanl** [comment]
Thanks a lot, @MeirShpilraien! Looking forward to have a look at it, once it is finished:-)
